//***************************************************/
//****************** LOCALE *************************/
//***************************************************/
export const SET_LOCALE_RUSSIAN = `SET_LOCALE_RUSSIAN`;
export const SET_LOCALE_ENGLISH = `SET_LOCALE_ENGLISH`;

//***************************************************/
//******************* USER **************************/
//***************************************************/
export const USER_LOGIN = "USER_LOGIN";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const AVATAR_UPDATE_REQUEST = "AVATAR_UPDATE_REQUEST";
export const AVATAR_UPDATE_SUCCESS = "AVATAR_UPDATE_SUCCESS";
export const AVATAR_UPDATE_FAIL = "AVATAR_UPDATE_FAIL";
export const AVATAR_UPDATE_RESET = "AVATAR_UPDATE_RESET";

export const USER_NEW_PASSWORD_REQUEST = "USER_NEW_PASSWORD_REQUEST";
export const USER_NEW_PASSWORD_SUCCESS = "USER_NEW_PASSWORD_SUCCESS";
export const USER_NEW_PASSWORD_FAIL = "USER_NEW_PASSWORD_FAIL";
export const USER_NEW_PASSWORD_RESET = "USER_NEW_PASSWORD_RESET";

export const USER_SET_PASSWORD_REQUEST = "USER_SET_PASSWORD_REQUEST";
export const USER_SET_PASSWORD_SUCCESS = "USER_SET_PASSWORD_SUCCESS";
export const USER_SET_PASSWORD_FAIL = "USER_SET_PASSWORD_FAIL";
export const USER_SET_PASSWORD_RESET = "USER_SET_PASSWORD_RESET";

//****************
//***** ORDER ****
//****************

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";

export const ORDER_STATE_RESET = "ORDER_STATE_RESET";

//***************************************************/
//******************* VIDEO *************************/
//***************************************************/

export const VIDEO_CREATE_REQUEST = "VIDEO_CREATE_REQUEST";
export const VIDEO_CREATE_SUCCESS = "VIDEO_CREATE_SUCCESS";
export const VIDEO_CREATE_FAIL = "VIDEO_CREATE_FAIL";
export const VIDEO_CREATE_RESET = "VIDEO_CREATE_RESET";

export const VIDEO_LIST_REQUEST = "VIDEO_LIST_REQUEST";
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS";
export const VIDEO_LIST_FAIL = "VIDEO_LIST_FAIL";

export const VIDEO_DELETE_REQUEST = "VIDEO_DELETE_REQUEST";
export const VIDEO_DELETE_SUCCESS = "VIDEO_DELETE_SUCCESS";
export const VIDEO_DELETE_FAIL = "VIDEO_DELETE_FAIL";

export const STATE_RESET_ERRORS = "STATE_RESET_ERRORS";
